#! /bin/sh


### auto start ###
# ./.config/bspwm/panel.sh &

feh --no-fehbg --bg-fill ~/.dotfiles/bg1.jpg
redshift -P -O 3500
pgrep -x tint2 > /dev/null || tint2 &
pgrep -x sxhkd > /dev/null || sxhkd &

### monitor setup ###
# for monitor in $(bspc query -M); do
# 	bspc monitor $monitor -d I II III IV V VI VII VIII IX X
# done
# 'hostname' command needs 'inetutils' package
if [ "$(hostname)" = 'archlinux' ]; then
  feh --no-fehbg --bg-fill ~/.dotfiles/bg1.jpg --bg-fill ~/.dotfiles/vertbg.png
	bspc monitor DP-2 -n 0 -d I II III IV V
	bspc monitor DP-4 -n 1 -d VI VII VIII IX X
else
	bspc monitor -n 0 -d I II III IV V VI VII VIII IX X
fi

### bspc configs ###
# bspc config border_radius			8
bspc config border_width			3
bspc config window_gap          	10
bspc config top_padding				20
bspc config bottom_padding			0
bspc config left_padding			0
bspc config right_padding			0

bspc config single_monocle			false
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

bspc config split_ratio          		0.50
bspc config click_to_focus				true
bspc config focus_follows_pointer		true
bspc config history_aware_focus			true
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true

bspc config pointer_modifier			mod4
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config pointer_action3				resize_corner

# bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

### bspc color scheme ###
# normal: unfocused window
# active: focused window of unfocused monitor
bspc config normal_border_color		"#282828"
bspc config active_border_color		"#d79921"
bspc config focused_border_color	"#98971a"
bspc config presel_feedback_color	"#98971a"
bspc config urgent_border_color		"#cc241d"
# bspc config focused_locked_border_color

# bspc config normal_frame_opacity
# bspc config focused_frame_opacity

### Rules ###
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
# bspc rule -a Alacritty
# bspc rule -a Firefox

# rules for file manager?
