require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.completion"
require "user.diagnostic"
require "user.lsp"
require "user.snip"
require "user.telescope"
require "user.git"
require "user.treesitter"
require "user.terminal"
require "user.disable_builtin"

require "impatient".enable_profile()
